### ISSUE TITLE
建议增加周期性任务功能

### ISSUE THREAD

**Issue by skyecx** [kuaifan/dootask#107]
日常工作中经常会出现一些循环任务，比如巡检，每天一次，每周一次之类

**Comment by skyecx** [comment]
因为有了任务导出功能，可用任务来做绩效考核，周期性每日/周都要做的事情任务创建人就比较轻松，不必每日都创建新的任务。

**Comment by wangrui1573** [comment]
这也是我想要的，同求帮顶！

**Comment by lotustalk** [comment]
这也是我想要的，同求帮顶！

**Comment by kuaifan** [comment]
## [0.18.1] Pro已经更新有，社区版即将到来

### Features

- 新增任务重复周期

### Performance

- 仪表盘列表新增显示协助的任务
