### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by sslsimon** [kuaifan/dootask#12]
部署执行./cmd install 报错如下：[错误]  设置env参数失败！
使用的是root用户

**Comment by kuaifan** [comment]
怀疑你网络有问题，拉不下docker镜像

**Comment by TTTsuperpyer** [comment]
一样的报错简直了  [错误] 设置env参数失败！

**Comment by kuaifan** [comment]
docker pull alpine 看一下你能否正常的拉镜像

**Comment by sslsimon** [comment]
翻了其它人的记录，升级了docker-composes可以装了，但装好后提示502 Bad Gateway

**Comment by sslsimon** [comment]
重新再执行./cmd install 神奇的好了。。

**Comment by a5601564** [comment]
一样的错误

**Comment by a5601564** [comment]
环境win10

**Comment by a5601564** [comment]
502 Bad Gateway 一样的问题

**Comment by kuaifan** [comment]
win我没有测过，你可以按照群友的方法试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lyon ***@***.***&gt;
发送时间: 2022年4月28日 08:21
收件人: kuaifan/dootask ***@***.***&gt;
抄送: kuaifan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kuaifan/dootask] 部署报错 (Issue #12)






环境win10
