### ISSUE TITLE
群晖docker上如何设置

### ISSUE THREAD

**Issue by hashdogcn** [kuaifan/dootask#14]
比如设置文件夹，端口，和变量，是否考虑出个教程呢

**Comment by kuaifan** [comment]
没钱买群辉。。。

**Comment by zgz200** [comment]
问题得到解决了吗？我也卡在群晖，好像docker里面有镜像，日志里面看不出来用了什么端口？

**Comment by kuaifan** [comment]
qq群里有群晖和win教程



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zgz200 ***@***.***&gt;
发送时间: 2022年4月9日 11:51
收件人: kuaifan/dootask ***@***.***&gt;
抄送: kuaifan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kuaifan/dootask] 群晖docker上如何设置 (Issue #14)





 
问题得到解决了吗？我也卡在群晖，好像docker里面有镜像，日志里面看不出来用了什么端口？

**Comment by huangteng815** [comment]
![image](https://user-images.githubusercontent.com/107458513/173726100-783021ea-fbf2-4fe1-a3dc-c4db71daecac.png)
能帮忙看下是缺少文件吗？
