### ISSUE TITLE
pro 版本，打开OFFICE文件预览会在 dootask目录下生成大量的core.***文件

### ISSUE THREAD

**Issue by zhqfdn** [kuaifan/dootask#151]
[root@localhost dootask]# ls core*
core.287  core.292  core.416  core.419  core.518  core.521  core.524  core.557  core.585  core.588  core.610  core.647
core.289  core.354  core.417  core.432  core.519  core.522  core.525  core.582  core.586  core.589  core.644  core.731
core.291  core.357  core.418  core.433  core.520  core.523  core.532  core.583  core.587  core.597  core.646  core.732

**Comment by kuaifan** [comment]
[0.25.48](https://github.com/kuaifan/dootask/releases/tag/v0.25.48) 已经修复此问题
