### ISSUE TITLE
请问内网下怎么部署安装呀？

### ISSUE THREAD

**Issue by 111-cxs** [kuaifan/dootask#192]
已经安装好docker、docker-compose，dootask安装的镜像文件也上传到docker里了。直接./cmd install安装还是会在线拉取资源报错

**Comment by SullivanJia** [comment]
同问

**Comment by 111-cxs** [comment]
您发来的邮件已收到！

**Comment by 111-cxs** [comment]
把镜像和php包离线下载完再导入到内网运行安装命令即可

**Comment by SullivanJia** [comment]
试了一下，需要commit的php镜像，导出后离线安装时，很奇怪还需要apline的latest镜像。

**Comment by 111-cxs** [comment]
你在能联网的电脑上安装成功了吗？成功了的话把所有镜像和php包导到内网去安装就行

**Comment by hsg8888** [comment]
> 你在能联网的电脑上安装成功了吗？成功了的话把所有镜像和php包导到内网去安装就行

镜像我会，php包怎么导到内网安装，没用过php，能具体说下吗

**Comment by 111-cxs** [comment]
您发来的邮件已收到！

**Comment by 111-cxs** [comment]
> > 你在能联网的电脑上安装成功了吗？成功了的话把所有镜像和php包导到内网去安装就行
> 
> 镜像我会，php包怎么导到内网安装，没用过php，能具体说下吗

和镜像一样导，打开联网电脑已安装好的dootask目录，然后把目录下所有php包全导过去就行（忘记在哪个文件夹下了，好像是最底下的一个文件夹，你一个个打开看就知道了）

**Comment by myjere** [comment]
今天刚试了一下，找一台外网电脑，全部安装好后把正在运行的docker容器打包成镜像（应该总共8个好像），在内网电脑里load一下（不运行），再把外网电脑中的dootask文件夹复制到内网电脑的相同路径下，把cmd中的rm -rf composer.lock注释掉（之前试过不注释，好像会联网下载php依赖？），然后按照安装步骤./cmd install就行。

**Comment by 111-cxs** [comment]
您发来的邮件已收到！
