### ISSUE TITLE
作者你好，想体验一下pro版本，用开源版本升级到最新的pro报错如下

### ISSUE THREAD

**Issue by cfy3133** [kuaifan/dootask#205]
![1711962082666](https://github.com/kuaifan/dootask/assets/43978367/0666695a-0098-4e34-800b-30152a18f1a5)

**Comment by kuaifan** [comment]
收到，尽快解决
________________________________
发件人: cfy3133 ***@***.***>
发送时间: Monday, April 1, 2024 5:02:46 PM
收件人: kuaifan/dootask ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kuaifan/dootask] 作者你好，想体验一下pro版本，用开源版本升级到最新的pro报错如下 (Issue #205)


1711962082666.jpg (view on web)<https://github.com/kuaifan/dootask/assets/43978367/0666695a-0098-4e34-800b-30152a18f1a5>

―

**Comment by kuaifan** [comment]
已解决
