### ISSUE TITLE
作者你好，重新从普通版本升级到pro版本使用如下指令升级后，还是显示0.13版本，没有报错，升级后系统正常访问

### ISSUE THREAD

**Issue by cfy3133** [kuaifan/dootask#206]
# 普通版升级至Pro版
![image](https://github.com/kuaifan/dootask/assets/43978367/33f286d3-ce75-4ed2-8640-bfd2c69a236e)
git checkout -b pro origin/pro
./cmd up -d
./cmd update
![image](https://github.com/kuaifan/dootask/assets/43978367/0d0ff241-b9a7-4cf8-a746-4f942f3cebeb)
![image](https://github.com/kuaifan/dootask/assets/43978367/a4378002-8fce-42e2-8ef0-bdc3ddab7869)
![image](https://github.com/kuaifan/dootask/assets/43978367/cd964493-8dac-4762-9095-95997f57e278)

**Comment by cfy3133** [comment]
git pull
./cmd mysql backup
./cmd uninstall
./cmd install
./cmd mysql recovery
通过这种方式也无法正常升级

**Comment by kuaifan** [comment]
已解决
