### ISSUE TITLE
如何修改页面代码

### ISSUE THREAD

**Issue by rookie-littleblack** [kuaifan/dootask#21]
你好，我想尝试着修改一下仪表盘页面的样式和布局，修改了“dootask/resources/assets/js/pages/manage”路径下的“dashboard.vue”文件，结果发现没有生效。系统重启过也无效，甚至我连docker服务都重启过。是不是改的不是该文件，那应该改哪个？谢谢！

**Comment by kuaifan** [comment]
vue项目需要编译，了解一下laravel+vue吧
