### ISSUE TITLE
账号已停用是什么情况？

### ISSUE THREAD

**Issue by SiriusZHT** [kuaifan/dootask#22]

**Comment by kuaifan** [comment]
![image](https://user-images.githubusercontent.com/36875852/146660974-1fff0e81-7ba7-42e7-90f3-982e8157c03a.png)

**Comment by SiriusZHT** [comment]
我之前在macOS的客户端里面使用的，用的是 ***@***.*** 注册的账号，希望你们别禁用我，我在上面还做了一些计划呢，谢谢!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月19日(星期天) 上午10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kuaifan/dootask] 账号已停用是什么情况？ (Issue #22)

**Comment by kuaifan** [comment]
这是个演示平台，会定期清空数据的
