### ISSUE TITLE
非常赞的项目，期待更全面的可用性

### ISSUE THREAD

**Issue by learn2s** [kuaifan/dootask#23]
大佬的这个项目初步上手感觉很赞，如果想贡献代码是不是需要  laravel+vue 的技术栈，开发调试 clone 下来修改再编译？

建议支持自建的 Excalidraw，自建的能够支持中文手写体；

看演示数据 GTD 里的内容，有说到标签和卡片 URL 链接的其他卡片，后续有这一块的迭代计划吗？不知道大佬用过 wekan 没，觉得可以参考；

另外邮箱通知或者 webhook 之类的有地方配置吗？还有反代的话，文件预览编辑的配置是？

打扰大佬，再次点赞项目！

**Comment by learn2s** [comment]
疏忽了，刚看了 .env，有相关配置内容，包括 URL 解决反代，以及邮件配置的，我先尝试下

**Comment by kuaifan** [comment]
Excalidraw、wekan 都没用过，🤣🤣🤣

**Comment by kuaifan** [comment]
webhook 考虑中
