### ISSUE TITLE
想请教大佬，如何配置局域网可访问？

### ISSUE THREAD

**Issue by babyfengfjx** [kuaifan/dootask#26]
环境搭起来了，在本机访问非常好，但是局域网其他电脑通过ip:端口没法访问，不知道如何配置，是否有大佬指点一二额~

**Comment by learn2s** [comment]
本机防火墙……

**Comment by babyfengfjx** [comment]
> 

用的deepin系统，木有防火墙设置哎，你们都是可以直接局域网就可以访问啊？

**Comment by kuaifan** [comment]
我本地都是可以的
