### ISSUE TITLE
以后是否新增文档管理？如markdown 文档及嵌入 markdown 编辑器等

### ISSUE THREAD

**Issue by yinxiulong** [kuaifan/dootask#30]
以后是否新增文档管理？如markdown 文档及嵌入 markdown 编辑器等。 对于开发人员来说，有个markdown 编辑器很重要

**Comment by kuaifan** [comment]
有的啊亲，里面的文档就是md的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yinxiulong ***@***.***&gt;
发送时间: 2021年12月22日 12:30
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 以后是否新增文档管理？如markdown 文档及嵌入 markdown 编辑器等 (Issue #30)





 
以后是否新增文档管理？如markdown 文档及嵌入 markdown 编辑器等。 对于开发人员来说，有个markdown 编辑器很重要
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Leadrive** [comment]
编辑器中没自动处理回车
