### ISSUE TITLE
支持 arm 服务器吗？

### ISSUE THREAD

**Issue by linyanginc** [kuaifan/dootask#39]
希望能支持arm 服务器.

**Comment by linyanginc** [comment]
去掉  onlyoffice 太大了 ，内存不够，不用容器安装行吗？

**Comment by kuaifan** [comment]
暂不支持，主要是onlyoffice不支持arm



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: linyanginc ***@***.***&gt;
发送时间: 2022年1月4日 11:20
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 支持 arm 服务器吗？ (Issue #39)






去掉  onlyoffice 太大了 ，内存不够，不用容器安装行吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
