### ISSUE TITLE
https反代配置之后，前端 js、css 请求的url 错误

### ISSUE THREAD

**Issue by ouuleilei** [kuaifan/dootask#41]
RT
![image](https://user-images.githubusercontent.com/31331320/148036020-8a86a0a8-dbcd-4e1b-adfa-c1c58355f00f.png)

**Comment by kuaifan** [comment]
```
# 1、Nginx config add
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

# 2、Enter directory and run command
./cmd https
```

**Comment by ouuleilei** [comment]
=，=  我的错，服务是容器启动的，改了端口号，nginx反代配置漏了一个。
**proxy_set_header Host $host:$server_port;**
加上这个配置后，正常了。
建议这个配置也加上去吧。

**Comment by Leadrive** [comment]
还要加上这个
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection Upgrade;
否则报wss错误

**Comment by AlienYMin** [comment]
你好，问下你这个问题是怎么解决的，我也遇到了相同的问题

**Comment by cethink** [comment]
解决了我的问题<3
