### ISSUE TITLE
建议增加dark界面，太刺眼睛了

### ISSUE THREAD

**Issue by GMIS** [kuaifan/dootask#42]
如题

**Comment by kuaifan** [comment]
好主意



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhang hongbing ***@***.***&gt;
发送时间: 2022年1月6日 03:57
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 建议增加dark界面，太刺眼睛了 (Issue #42)





 
如题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kuaifan** [comment]
0.6.38 以支持

**Comment by GMIS** [comment]
体验了一下暗黑模式，感觉还差点意思，在暗黑模式下，表格显示不够醒目，希望能在配色上改进一下。
![image](https://user-images.githubusercontent.com/7294225/150273102-09cdeaeb-0eaa-4cc8-80e6-968a96e63f8e.png)
