### ISSUE TITLE
项目模板在那里自己定义呢，现在只有空白模板，软件开发，产品开发

### ISSUE THREAD

**Issue by gzbenson** [kuaifan/dootask#43]
项目模板可以自己自定义设置吗？

**Comment by kuaifan** [comment]
目前不可以



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gzbenson ***@***.***&gt;
发送时间: 2022年1月7日 14:12
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 项目模板在那里自己定义呢，现在只有空白模板，软件开发，产品开发 (Issue #43)





 
项目模板可以自己自定义设置吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
