### ISSUE TITLE
新手搭建常见问题，打开链接502

### ISSUE THREAD

**Issue by jlintxia** [kuaifan/dootask#46]
新手容易遇到的问题。打开链接显示502
![image](https://user-images.githubusercontent.com/28779574/148733109-209dee7b-1c77-47c4-b12e-1ad7833732c9.png)

**Comment by kuaifan** [comment]
有部分机子无法自动启动supervisor，需要手动启动
```
./cmd install 
./cmd service supervisor satrt
```

**Comment by small-rose** [comment]
部署成功了，但是无法访问，我是云机器centos7，防火墙暂时关闭，安全组端口也开了。
