### ISSUE TITLE
求教执行install命令时出现报错

### ISSUE THREAD

**Issue by anmeng777** [kuaifan/dootask#48]
在dootask目录下执行./cmd install时，出现报错"-bash: ./cmd: /bin/bash^M: bad interpreter: No such file or directory"。
docker --version : Docker version 18.03.1-ce, build 9ee9f40
docker-compose --version : docker-compose version 1.27.4, build 40524192
unbuntu version : 16.04

**Comment by kuaifan** [comment]
可以试试 
```
cp .env.docker .env
dos2unix cmd
dos2unix .env
./cmd install
```
