### ISSUE TITLE
大文件上传报错，The file "XXXX" could not be written on disk.

### ISSUE THREAD

**Issue by ekikoshin** [kuaifan/dootask#50]
经测试当文件大于64MB时，上传文件会出现该报错。The file "XXXX" could not be written on disk。
环境，UBUNTU18.04，轻量级服务器，上传速度3MB/S，磁盘大小40G。

<img width="419" alt="3AB1CBFCBBE99AA25805B60431EBDDFB" src="https://user-images.githubusercontent.com/24950074/149637048-eff8a907-4f1a-4a0e-aace-24c2171cdc8b.png">
.

**Comment by kuaifan** [comment]
最新master分支已经修复这个问题，可以通过 ./cmd update 升级
