### ISSUE TITLE
安装时docker报错，缺失composer.lock文件

### ISSUE THREAD

**Issue by mox-hub** [kuaifan/dootask#56]
安装环境：CentOS 7.9，php8.0，docker20.10.12,docker-compose 2.2.3
报错信息：
`No composer.lock file present.Updating dependencies to latest instead of installing from lock file.`

出现此问题后，尝试使用`composer install --ignore-platform-reqs`后没有效果，并且报同样错误

**Comment by kuaifan** [comment]
这个只是弱提醒，其实不影响
