### ISSUE TITLE
Upload组件在哪定义的啊

### ISSUE THREAD

**Issue by jujubos** [kuaifan/dootask#57]
Upload组件在哪定义的啊，我没找到类似Upload.vue的

**Comment by kuaifan** [comment]
用iviewui



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jujubos ***@***.***&gt;
发送时间: 2022年2月1日 14:48
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] Upload组件在哪定义的啊 (Issue #57)





 
Upload组件在哪定义的啊，我没找到类似Upload.vue的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jujubos** [comment]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/79678933/152119139-01f1cb25-2e27-4a05-b497-366fa5017f23.png">

Upload的handleClick()是自己实现的吗？在哪啊？

**Comment by kuaifan** [comment]
https://github.com/kuaifan/ViewUI
可以自己开源
