### ISSUE TITLE
希望能够支持上传 .drawio 文件

### ISSUE THREAD

**Issue by xhb** [kuaifan/dootask#61]
已经支持 流程图 编辑了，但是为什么不能支持 .drawio 的文件上传？？

**Comment by kuaifan** [comment]
0.9.×已经支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xhb ***@***.***&gt;
发送时间: 2022年2月21日 17:06
收件人: kuaifan/dootask ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kuaifan/dootask] 希望能够支持上传 .drawio 文件 (Issue #61)





 
已经支持 流程图 编辑了，但是为什么支持 .drawio 的文件上传？？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
