### ISSUE TITLE
安装脚本cmd写的有问题，docker compose以及镜像拉取问题

### ISSUE THREAD

**Issue by c12q** [kuaifan/dootask#64]
## 判断docker compose是否安装的判断语句有问题，由于要求是安装docker compose v2所以判断版本命令是docker compose version而非docker-compose --version
<img width="832" alt="image" src="https://user-images.githubusercontent.com/57549979/155641649-884fe000-424a-43c2-9f77-8fbe1629bfe8.png">
## 脚本中docker compose的命令都有问题，docker-compose应该都改为docker-compose
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/57549979/155641804-51a72f50-9920-48da-84ff-83a3287f75a1.png">
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/57549979/155641823-03887fcf-234e-4627-98c8-f987a453936d.png">
## 我把脚本中关于docker-compose的错误改正之后，发现拉去镜像也有问题，可能是镜像地址有误，请确认
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/57549979/155641957-e58ba41e-c160-4f85-8751-ffe153fe51f9.png">

**Comment by kuaifan** [comment]
1、docker-compose version 已修复
2、后者是拉到一半网络断了，可以更换docker源
