### ISSUE TITLE
管理员无法删除非自己所有的项目

### ISSUE THREAD

**Issue by jokin1999** [kuaifan/dootask#86]
管理员无法删除非自己所有的项目，只能在所有项目里看到列表，是否有其他方式可以查看项目？

**Comment by kuaifan** [comment]
程序设计是只有项目负责人才能管理项目

**Comment by jokin1999** [comment]
项目负责人账户被撤销或删除后，无人能管理项目的情况如何解决？

**Comment by kuaifan** [comment]
团队管理，操作离职，可以设置交接人
