### ISSUE TITLE
全新安装的dootask 无法打开onlyoffice

### ISSUE THREAD

**Issue by jwenlee** [kuaifan/dootask#90]
https://www.dageebox.com/single/file/E97vABDsjOZ8SG2OHF3c5a0ACyjICGlFK10QpMEfxQNtse7cG21AuTxM0TlNKlTM

 docker - office显示的日志
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/3352179/163366731-0facca0e-9fe7-480a-a24f-8cf8a29067d1.png">

**Comment by kuaifan** [comment]
这个报错可以报告给onlyoffice官方
